server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进eureka服务器的服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:HOSystemH/springcloud-config.git
          search-paths:
            - springcloud-config
          default-label: master

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/

