server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zzyybs/springcloud-config.git  #GitHub上面的git仓库名字
#          username: hosystem@163.com
#          password: HePluto123456